version: '3'

services:
  user_db:
    image: postgres:12.11
    volumes:
      - ./scripts/postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: "${DB_NAME:-user_service_local_dev}"
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"
    labels:
      container_group: user-service
    expose:
      - "5432"
  user:
    build:
      context: ./
      dockerfile: ./services/user/Dockerfile
    image: user-service
    links:
      - user_db
    environment:
      API_PORT: "${API_PORT:-3000}"
      NODE_ENV: "${NODE_ENV:-development}"
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"
      DB_NAME: "${DB_NAME:-user_service_local_dev}"
      DB_HOST: "${DB_HOST:-vescape-ecommerce_user_db_1}"
      DB_PORT: "${DB_PORT:-5432}"
    ports:
      - "3000:3000"
    labels:
      container_group: user-service
networks:
  default:
      external:
        name: defaultNet
