version: '3'

services:
  user_db:
    image: postgres:12.11
    volumes:
      - ./scripts/postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: "${DB_NAME:-user_service_local_dev}"
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"
    labels:
      container_group: user-service
    expose:
      - "5432"
  user:
    build:
      context: ./
      dockerfile: ./services/user/Dockerfile
    image: user-service
    links:
      - user_db
    environment:
      API_PORT: "${API_PORT:-3000}"
      NODE_ENV: "${NODE_ENV:-development}"
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"
      DB_NAME: "${DB_NAME:-user_service_local_dev}"
      DB_HOST: "${DB_HOST:-vescape-ecommerce_user_db_1}"
      DB_PORT: "${DB_PORT:-5432}"
      JWT_SECRET: "${JWT_SECRET:-secret}"
      AMQP_HOST: "${AMQP_HOST}"
    ports:
      - "3000:3000"
    labels:
      container_group: user-service
    extra_hosts:
    - "host.docker.internal:host-gateway"
  product_db:
    image: postgres:12.11
    volumes:
      - ./scripts/postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: "${DB_NAME:-product_service_local_dev}"
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"
    labels:
      container_group: product-service
    expose:
      - "5432"
  product:
    build:
      context: ./
      dockerfile: ./services/product/Dockerfile
    image: product-service
    links:
      - product_db
    environment:
      API_PORT: "${API_PORT:-3001}"
      NODE_ENV: "${NODE_ENV:-development}"
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"
      DB_NAME: "${DB_NAME:-product_service_local_dev}"
      DB_HOST: "${DB_HOST:-vescape-ecommerce_product_db_1}"
      DB_PORT: "${DB_PORT:-5432}"
      JWT_SECRET: "${JWT_SECRET:-secret}"
    ports:
      - "3001:3001"
    labels:
      container_group: product-service
    extra_hosts:
    - "host.docker.internal:host-gateway"
  order_db:
    image: postgres:12.11
    volumes:
      - ./scripts/postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: "${DB_NAME:-order_service_local_dev}"
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"
    labels:
      container_group: order-service
    expose:
      - "5432"
  order:
    build:
      context: ./
      dockerfile: ./services/order/Dockerfile
    image: order-service
    links:
      - order_db
    environment:
      API_PORT: "${API_PORT:-3002}"
      NODE_ENV: "${NODE_ENV:-development}"
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"
      DB_NAME: "${DB_NAME:-order_service_local_dev}"
      DB_HOST: "${DB_HOST:-vescape-ecommerce_order_db_1}"
      DB_PORT: "${DB_PORT:-5432}"
      JWT_SECRET: "${JWT_SECRET:-secret}"
      AMQP_HOST: "${AMQP_HOST}"
    ports:
      - "3002:3002"
    labels:
      container_group: order-service
    extra_hosts:
    - "host.docker.internal:host-gateway"
networks:
  default:
      external:
        name: defaultNet
